{% set name = "cylc-flow" %}
{% set version = "8.0b3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8b694afb63f66ce4d9268e920f76a0c4d43d11f70efed4e3e0ff0f52928b5db4

build:
  noarch: python
  number: 1

# ngam (20211119): adding libuv as backup for pyuv problems

requirements:
  host:
    - pip
    - python
    - libuv
  run:
    - python

test:
  imports:
    - cylc.flow
  commands:
    - cylc --version
    - cylc version --long
    - cylc extract-resources etc/job.sh  # check packaging of non-python files

outputs:
  # base package with only required dependencies
  - name: {{ name }}-base
    build:
      noarch: python
      script: python -m pip install . --no-deps --ignore-installed -vv
    requirements:
      host:
        - pip
        - python
        - libuv
      run:
        - python
        - aiofiles >=0.7.0,<0.8.0
        - ansimarkup >=1.0.0
        - colorama >=0.4,<=1.0
        - graphene >=2.1,<3
        - jinja2 ==2.11.0,<2.12
        - metomi-isodatetime >=1!2.0.2, <1!2.1.0
        - protobuf >=3.15.0,<3.16.0
        - psutil >=5.6.0
        - pyuv >=1.4.0,<1.5.0
        - pyzmq >=19.0.0,<19.1.0
        - setuptools >=49
        - urwid >=2,<3

  # full package with all dependencies installed
  - name: {{ name }}
    build:
      noarch: python
      script: python -m pip install .[empy,report-timings] --no-deps --ignore-installed -vv
    requirements:
      host:
        - pip
        - libuv
        - python
      run:
        - python
        - {{ pin_subpackage(name + "-base", exact=True) }}
        - empy >=3.3,<3.4
        - graphviz  # for static graphing
        - pandas >=1.0,<2
        - matplotlib-base
        - pillow
        - pympler

about:
  home: https://cylc.org/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: A workflow engine for cycling systems
  description: |
    Cylc ("silk") is a workflow engine for cycling systems - it orchestrates
    distributed workflows of interdependent cycling tasks that may continue to
    run indefinitely.
  doc_url: https://cylc.github.io/cylc-doc/
  dev_url: https://github.com/cylc/cylc-flow

extra:
  recipe-maintainers:
    - hjoliver
    - kinow
    - oliver-sanders
    - ngam
