{% set name = "cylc-flow" %}
{% set version = "8.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 66d0f4ce8e2fa4ac2f0a29e184ea534a2f4814dd2a116c8d721f11fd6a161f21

build:
  number: 0
  noarch: python

requirements:
  host:
    - __unix
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - __unix
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  files:
    - tests/simple-datetime/flow.cylc
  imports:
    - cylc.flow
  commands:
    - cylc --version
    - cylc version --long
    - cylc get-resources job.sh  # check packaging of non-python files
    - cylc help licence  # check packaging of licence file
    - cylc validate ./tests/simple-datetime

outputs:
  # base package with only required dependencies
  - name: {{ name }}-base
    build:
      script: python -m pip install . --no-deps --ignore-installed -vv
      noarch: python
    requirements:
      host:
        - __unix
        - pip
        - python {{ python_min }}
        - setuptools
      run:
        - __unix
        - python >={{ python_min }}
        - ansimarkup >=1.0.0
        - colorama >=0.4,<1.0
        - graphene >=3.4.0,<3.5
        - graphql-core >=3.2,<3.3
        - jinja2 >=3.0,<3.1
        - metomi-isodatetime >=1!3.0.0,<1!3.2.0
        - packaging
        - protobuf >=5,<8
        - psutil >=5.6.0
        - pyzmq >=22
        - urwid >=2.2,<4,!=2.6.2,!=2.6.3

  # full package with all dependencies installed
  # (excluding tests, developer extensions, etc)
  - name: {{ name }}
    build:
      script: python -m pip install .[report-timings,tutorials,graph] --no-deps --ignore-installed -vv
      noarch: python
    requirements:
      host:
        - __unix
        - pip
        - python {{ python_min }}
        - setuptools
      run:
        - __unix
        - python >={{ python_min }}
        - {{ pin_subpackage(name + "-base", exact=True) }}
        # Dependencies for the `pip install` command above:
        # static graphing
        - graphviz
        - pillow

        # tutorials
        - requests
        - h5py

about:
  home: https://cylc.org/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: A workflow engine for cycling systems
  description: |
    Cylc ("silk") is a workflow engine for cycling systems - it orchestrates
    distributed workflows of interdependent cycling tasks that may continue to
    run indefinitely.

    There are two cylc-flow packages:
    * `cylc-flow`: The full installation, recommended for most uses.
    * `cylc-flow-base`: A minimal package, recommended for installation on job
      hosts where the full range of user-facing commands is not required.

    The `cylc report-timings` command requires two additional dependencies
    which you must specify manually if you want this functionality:
    * `pandas >=1.0,<2`
    * `matplotlib-base`
  doc_url: https://cylc.github.io/cylc-doc/
  dev_url: https://github.com/cylc/cylc-flow

extra:
  recipe-maintainers:
    - MetRonnie
    - hjoliver
    - oliver-sanders
