{% set name = "cylc-flow" %}
{% set version = "8.0b0" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4756fc92cca9d8dc520c5e294f55ae42fe411c802212d6d0004f01fdad4fc352

build:
  number: 2
  skip: True  # [py<37 or not linux]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

outputs:
  - name: cylc-flow-base
    requirements:
      host:
        - pip
        - python
      run:
        - aiofiles >=0.5.0,<0.6.0
        - ansimarkup >=1.0.0
        - colorama >=0.4,<1
        - click >=7.0
        - cryptography
        - graphene >=2.1,<3
        - jinja2 ==2.11.0,<2.12
        - metomi-isodatetime >=1!2.0.2, <1!2.1.0
        - packaging
        - protobuf >=3.15.0,<3.16.0
        - pyasn1  # TODO: not required? #8
        - python
        - pyuv >=1.4.0,<1.5.0
        - pyzmq >=19.0.0,<19.1.0
        - psutil >=5.6.0
        - urwid >=2.0,<2.1
        - rx >=1.6,<2 # TODO: https://github.com/conda-forge/cylc-feedstock/pull/3#issuecomment-660716268
    test:
      imports:
        - cylc.flow
      commands:
        - cylc --version
  - name: cylc-flow-empy
    requirements:
      host:
        - pip
        - python
      run:
        - python
        - {{ pin_subpackage("cylc-flow-base", exact=True) }}
        - empy >=3.3,<3.4
    test:
      imports:
        - cylc.flow
        - empy
      commands:
        - cylc --version
  - name: cylc-flow-report-timings
    requirements:
      host:
        - pip
        - python
      run:
        - python
        - {{ pin_subpackage("cylc-flow-base", exact=True) }}
        - pandas >=0.25.0,<0.26
    test:
      imports:
        - cylc.flow
        - pandas
      commands:
        - cylc --version
  - name: cylc-flow-main_loop
    requirements:
      host:
        - pip
        - python
      run:
        - python
        - {{ pin_subpackage("cylc-flow-base", exact=True) }}
        - pympler
        - matplotlib-base
    test:
      imports:
        - cylc.flow
        - matplotlib
        - pympler
      commands:
        - cylc --version


about:
  home: https://cylc.github.io/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'A workflow engine for cycling systems'
  description: |
    Cylc ("silk") orchestrates complex distributed suites of interdependent
    cycling (or non-cycling) tasks. It was originally designed to automate
    environmental forecasting systems at NIWA, however Cylc is a general
    workflow engine; it is not specialized to forecasting in any way.
  doc_url: https://cylc.github.io/documentation.html
  dev_url: https://github.com/cylc/cylc-flow

extra:
  recipe-maintainers:
    - hjoliver
    - kinow
    - oliver-sanders
