{% set name = "cylc-flow" %}
{% set version = "8.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eaaebaca4f52d353ac63da5e355d3414a9dbc92a98f8d9641b284fa26b1062c8

build:
  number: 0
  noarch: python

requirements:
  host:
    - __unix
    - pip
    - python >=3.7
  run:
    - __unix
    - python >=3.7

test:
  files:
    - tests/simple-datetime/flow.cylc
  imports:
    - cylc.flow
  commands:
    - cylc --version
    - cylc version --long
    - cylc get-resources job.sh  # check packaging of non-python files
    - cylc validate ./tests/simple-datetime

outputs:
  # base package with only required dependencies
  - name: {{ name }}-base
    build:
      script: python -m pip install . --no-deps --ignore-installed -vv
      noarch: python
    requirements:
      host:
        - __unix
        - pip
        - python >=3.7
      run:
        - __unix
        - python >=3.7
        - aiofiles >=0.7.0,<0.8.0
        - ansimarkup >=1.0.0
        - async-timeout >=3.0.0
        - colorama >=0.4,<1.0
        - graphene >=2.1,<3
        - jinja2 >=3.0,<3.1
        - metomi-isodatetime >=1!3.0.0, <1!3.1.0
        - protobuf >=4.21.2,<4.22.0
        - psutil >=5.6.0
        - pyzmq >=22,<23
        - setuptools >=49, <67
        - urwid >=2,<3
        # non-pinned transitive dependencies used for type checking
        - rx
        - promise
        - tomli >=2.0, <3.0

  # full package with all dependencies installed
  # (excluding tests, developer extensions, etc)
  - name: {{ name }}
    build:
      script: python -m pip install .[empy,report-timings,tutorials,graph] --no-deps --ignore-installed -vv
      noarch: python
    requirements:
      host:
        - __unix
        - pip
        - python >=3.7
      run:
        - __unix
        - python >=3.7
        - {{ pin_subpackage(name + "-base", exact=True) }}
        # Dependencies for the `pip install` command above:
        - empy >=3.3,<3.4
        # static graphing
        - graphviz
        - pillow
        # report-timings
        - pandas >=1.0,<2
        - matplotlib-base
        # tutorials
        - requests

about:
  home: https://cylc.org/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: A workflow engine for cycling systems
  description: |
    Cylc ("silk") is a workflow engine for cycling systems - it orchestrates
    distributed workflows of interdependent cycling tasks that may continue to
    run indefinitely.
  doc_url: https://cylc.github.io/cylc-doc/
  dev_url: https://github.com/cylc/cylc-flow

extra:
  recipe-maintainers:
    - MetRonnie
    - hjoliver
    - oliver-sanders
