{% set name = "cylc-flow" %}
{% set version = "8.0b1" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bc00c933e2d21a58b1b0196a60c06c3d1162d6db1660b9a8de536a1e4d1d2425

build:
  number: 0
  skip: True  # [py<37 or not unix]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python
  run:
    - aiofiles >=0.5.0,<0.6.0
    - ansimarkup >=1.0.0
    - click >=7.0
    - colorama >=0.4,<0.5
    - cryptography
    - graphene >=2.1,<3
    - jinja2 ==2.11.0,<2.12
    - metomi-isodatetime >=1!2.0.2, <1!2.1.0
    - protobuf >=3.15.0,<3.16.0
    - psutil >=5.6.0
    - pyasn1
    - python
    - pyuv >=1.4.0,<1.5.0
    - pyzmq >=19.0.0,<19.1.0
    - urwid >=2.0,<2.1
    # TODO: optional dependencies, see discussion here https://github.com/conda-forge/cylc-flow-feedstock/pull/4
    - empy >=3.3,<3.4
    - pandas >=0.25.0,<0.26
    - pympler
    - matplotlib-base
    - rx >=1.6,<2 # TODO: https://github.com/conda-forge/cylc-feedstock/pull/3#issuecomment-660716268
    - packaging

test:
  imports:
    - cylc.flow
  commands:
    - cylc --version

about:
  home: https://cylc.github.io/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'A workflow engine for cycling systems'
  description: |
    Cylc ("silk") orchestrates complex distributed suites of interdependent
    cycling (or non-cycling) tasks. It was originally designed to automate
    environmental forecasting systems at NIWA, however Cylc is a general
    workflow engine; it is not specialized to forecasting in any way.
  doc_url: https://cylc.github.io/documentation.html
  dev_url: https://github.com/cylc/cylc-flow

extra:
  recipe-maintainers:
    - hjoliver
    - kinow
    - oliver-sanders
