{% set name = "cylc-flow" %}
{% set version = "8.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7aee0148af3336694ea18b6b49e020fabe7109dc6e604b0836e4d6f83d83cfe1

build:
  number: 1
  noarch: python

requirements:
  host:
    - __unix
    - pip
    - python >=3.7
  run:
    - __unix
    - python >=3.7

test:
  imports:
    - cylc.flow
  commands:
    - cylc --version
    - cylc version --long
    - cylc get-resources job.sh  # check packaging of non-python files

outputs:
  # base package with only required dependencies
  - name: {{ name }}-base
    build:
      script: python -m pip install . --no-deps --ignore-installed -vv
      noarch: python
    requirements:
      host:
        - __unix
        - pip
        - python >=3.7
      run:
        - __unix
        - python >=3.7
        - aiofiles >=0.7.0,<0.8.0
        - ansimarkup >=1.0.0
        - async-timeout >=3.0.0
        - colorama >=0.4,<1.0
        - graphene >=2.1,<3
        - jinja2 ==2.11.0,<2.12
        - metomi-isodatetime >=1!2.0.2, <1!2.1.0
        - protobuf >=3.19.0,<3.20.0
        - psutil >=5.6.0
        - pyuv >=1.4.0,<1.5.0
        - pyzmq >=22,<23
        - setuptools >=49
        - urwid >=2,<3

        # https://github.com/pallets/jinja/issues/1585 (remove when upgrading
        # jinja2 to >= 3.0):
        - markupsafe <2.1

  # full package with all dependencies installed
  # (excluding tests, developer extensions, etc)
  - name: {{ name }}
    build:
      script: python -m pip install .[empy,report-timings,tutorials,graph] --no-deps --ignore-installed -vv
      noarch: python
    requirements:
      host:
        - __unix
        - pip
        - python >=3.7
      run:
        - __unix
        - python >=3.7
        - {{ pin_subpackage(name + "-base", exact=True) }}
        - empy >=3.3,<3.4
        # static graphing
        - graphviz
        # report-timings
        - pandas >=1.0,<2
        - matplotlib-base
        # tutorials
        - pillow
        - urllib3

about:
  home: https://cylc.org/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: A workflow engine for cycling systems
  description: |
    Cylc ("silk") is a workflow engine for cycling systems - it orchestrates
    distributed workflows of interdependent cycling tasks that may continue to
    run indefinitely.
  doc_url: https://cylc.github.io/cylc-doc/
  dev_url: https://github.com/cylc/cylc-flow

extra:
  recipe-maintainers:
    - MetRonnie
    - hjoliver
    - oliver-sanders
